name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/ci.yml'
      - '.github/actions/test/**'
      - '.test/**'
      - 'client/**'
      - 'server/**'
      - 'dist/**'
      - 'Makefile.PL'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/test
